
DESCRIPTIONS = {
    'length_url': 'URL Length',
    'length_hostname': 'Hostname Length',
    'ip': 'Contains IP',
    'nb_dots': 'Number of Dots',
    'nb_hyphens': 'Number of Hyphens',
    'nb_at': 'Number of @ Symbols',
    'nb_qm': 'Number of Question Marks',
    'nb_and': 'Number of Ampersands',
    'nb_or': 'Number of Vertical Bars',
    'nb_eq': 'Number of Equal Signs',
    'nb_underscore': 'Number of Underscores',
    'nb_tilde': 'Number of Tildes',
    'nb_percent': 'Number of Percentage Symbols',
    'nb_slash': 'Number of Forward Slashes',
    'nb_star': 'Number of Star Symbols',
    'nb_colon': 'Number of Colons',
    'nb_comma': 'Number of Commas',
    'nb_semicolon': 'Number of Semicolons',
    'nb_dollar': 'Number of Dollar Signs',
    'nb_space': 'Number of Spaces',
    'nb_www': 'www exists',
    'nb_com': 'com exists',
    'nb_dslash': 'Number of Double Slashes',
    'http_in_path': 'Is HTTP in Path',
    'https_token': 'HTTPS token',
    'ratio_digits_url': 'Percentage of Digits (Whole)',
    'ratio_digits_host': 'Percentage of Digits (Hostname)',
    'punycode': 'Is Puny Code',
    'port': 'Contains Port',
    'tld_in_path': 'Is TLD in Path',
    'tld_in_subdomain': 'Is TLD in Subdomain',
    'abnormal_subdomain': 'Is Abnormal Subdomain',
    'nb_subdomain': 'Number of Subdomains',
    'prefix_suffix': 'Prefix/Suffix',
    'shortening_service': 'Is a Shortening Service',
    'path_extension': 'Contains path extension',
    'nb_redirection': 'Number of Redirects',
    'nb_external_redirection': 'Number of External Redirects',
    'length_words_raw': 'Length of Raw Words',
    'char_repeat': 'Number of Repeating Characters Consecutively',
    'shortest_words_raw': 'Shortest Word Length',
    'shortest_word_host': 'Shortest Word Length (Host)',
    'shortest_word_path': 'Shortest Word Length (Path)',
    'longest_words_raw': 'Longest Word Length',
    'longest_word_host': 'Longest Word Length (Host)',
    'longest_word_path': 'Longest Word Length (Path)',
    'avg_words_raw': 'Average Word Length',
    'avg_word_host': 'Average Word Length (Host)',
    'avg_word_path': 'Average Word Length (Path)',
    'phish_hints': 'Count of Phishing Hints',
    'domain_in_brand': 'Contains a Known Brand',
    'brand_in_subdomain': 'Contains a Known Brand (Subdomain)',
    'brand_in_path': 'Contains a Known Brand (Path)',
    'suspicious_tld': 'Is a Suspicious TLD',
    'statistical_report': 'Statistical Report'
}